### ISSUE TITLE
Xiaomi 14 Ultra framework.jar error

### ISSUE THREAD

**Issue by ghost** [Jefino9488/FrameworkPatcher#12]
Error: Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/util/LongSparseArray;->clone()Landroid/util/LongSparseArray;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
	at org.jf.smali.Smali.assemble(Smali.java:131)
	at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
	at org.jf.smali.Main.main(Main.java:100)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x14
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1[33](https://github.com/Jefino9488/FrameworkPatcher/actions/runs/11263317529/job/31320923917#step:30:34)1)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
	... 5 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65554
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:[35](https://github.com/Jefino9488/FrameworkPatcher/actions/runs/11263317529/job/31320923917#step:30:36)6)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
	... 6 more

Error: Process completed with exit code 1.

gives this error why ?

**Comment by Jefino9488** [comment]
Known issues will fix after a month ig

**Comment by ghost** [comment]
**okay thanks bro**

**Comment by Jefino9488** [comment]
the issue should be fixed by this [comit](https://github.com/Jefino9488/FrameworkPatcher/commit/3d22e17593c9363fbc37cda2e701c37d0f71cc53) retry build.
