### ISSUE TITLE
14 Ultra again error framework files

### ISSUE THREAD

**Issue by ghost** [Jefino9488/FrameworkPatcher#14]
Error: Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/util/LongSparseArray;->clone()Landroid/util/LongSparseArray;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
	at org.jf.smali.Smali.assemble(Smali.java:131)
	at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
	at org.jf.smali.Main.main(Main.java:100)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x14
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1[33](https://github.com/Jefino9488/FrameworkPatcher/actions/runs/11373811408/job/31641195230#step:21:34)1)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
	... 5 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65554
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:[35](https://github.com/Jefino9488/FrameworkPatcher/actions/runs/11373811408/job/31641195230#step:21:36)6)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
	... 6 more

Error: Process completed with exit code 1.

**I tried this 15 minutes ago, still the same error. Let me give you the link to the framework files, you try it.**

**https://gitlab.com/Juliano31/dosyalar/-/raw/main/framework.jar
https://gitlab.com/Juliano31/dosyalar/-/raw/main/services.jar
https://gitlab.com/Juliano31/dosyalar/-/raw/main/miui-services.jar
https://gitlab.com/Juliano31/dosyalar/-/raw/main/miui-framework.jar**

**Comment by Jefino9488** [comment]
thanks for reporting will look in to it

**Comment by ghost** [comment]
**Of course you're welcome**

**Comment by ghost** [comment]
**When I tried it with your work here, it worked without any problems, I thought I'd let you know.
Here Link :
https://github.com/Jefino9488/HyperMod-Builder/tree/master/Builder/framework_patcher**

**Comment by Jefino9488** [comment]
Ohh

**Comment by Jefino9488** [comment]
could u try again an report

**Comment by ghost** [comment]
**but you haven't changed anything, if I try it like this it will give me an error again, are you sure?**

**Comment by Jefino9488** [comment]
do via website try

**Comment by Jefino9488** [comment]
> **but you haven't changed anything, if I try it like this it will give me an error again, are you sure?**

i did changes i was stupid enough to add all those files to same dex, ig that should be causing issue i just removed settings helper.

**Comment by ghost** [comment]
****Yes, you were right. It is now completed without any problems and it worked.**
https://github.com/Jefino9488/FrameworkPatcher/actions/runs/11404519657**
